# fly.toml app configuration file generated for backend-lively-silence-4780 on 2025-12-11T06:09:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-lively-silence-4780'
primary_region = 'yyz'

[build]

[http_service]
  processes = ['app']
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  max_machines_running = 1
  min_machines_running = 0
   

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
